Ferlab-Ste-Justine/clin-portal-ui

.github/workflows/build.yml
.github/workflows/commit_lint.yml
.github/workflows/publish_image_sha.yml
.github/workflows/publish_image_tag.yml
env-prod
env-qa
env-staging

feat: CLIN-1013 Added deployment pipeline

---

.jest/identity-obj-proxy-esm.js
package-lock.json
package.json
src/components/Layout/Footer/tests/__snapshots__/Footer.test.jsx.snap

closes https://ferlab-crsj.atlassian.net/browse/CLIN-1014

feat: CLIN-1014 setup tests

---

src/locales/fr.json

fix: CLIN-1012 typo Cohortes publiques

---

env-prod
env-qa
env-staging

feat: INFRA-25 Adjusted domain

---

.husky/pre-commit

closes https://ferlab-crsj.atlassian.net/browse/CLIN-632

feat: CLIN-632 eslint pre-commit hooks

---

package.json

desactivé eslint sur la compilation de dev

fix: CLIN-633 desactivé eslint sur la compilation de dev

---

package-lock.json
src/views/Variants/Exploration/variantColumns.tsx

closes https://ferlab-crsj.atlassian.net/browse/CLIN-1036

fix: CLIN-1036 point to variant if no varsome

---

package-lock.json
package.json
src/utils/formatNumber.ts
src/utils/translation.ts
src/views/Prescriptions/Entity/AnalysisCard/index.tsx
src/views/Prescriptions/Entity/PatientCard/PatientContent/index.tsx
src/views/Prescriptions/Entity/RequestTable.tsx
src/views/Prescriptions/Entity/index.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
src/views/Prescriptions/Search/components/table/SequencingTable/columns.tsx
src/views/Variants/Entity/PatientPanel/columns.tsx
src/views/Variants/Entity/SummaryPanel/Frequency/index.tsx
src/views/Variants/Entity/SummaryPanel/Summary/index.tsx
src/views/Variants/Exploration/Patient/index.tsx
src/views/Variants/Exploration/variantColumns.tsx

Formater les chiffre a divers endroit dans l'application

fix: CLIN-1075 format Number

---

src/style/README.md

docs: CLIN-1112 update style documentation

---

src/locales/fr.json

docs: CLIN-1112 update style documentation fix

---

src/auth/rpt.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-1126
Force logout if refresh token failed.

fix: CLIN-1126 force logout if token refresh failed

---

src/components/uiKit/search/PrescriptionAutoComplete/index.tsx

closes https://ferlab-crsj.atlassian.net/browse/CLIN-1111
Permet de rechercher par numéro de requete

fix: CLIN-1111 ajouter recherche prescription par numero de requete

---

src/components/uiKit/search/PrescriptionAutoComplete/index.tsx
src/locales/en.json
src/locales/fr.json
src/views/Home/components/PrescriptionSearchBox/index.tsx
src/views/Home/components/SearchBox/index.tsx
src/views/Prescriptions/Search/index.tsx

closes: https://ferlab-crsj.atlassian.net/browse/CLIN-1151 https://ferlab-crsj.atlassian.net/browse/CLIN-1152

fix: CLIN-1151 update prescription search design

---

src/views/Variants/Exploration/components/AcmgVerdict/index.module.scss
src/views/Variants/Exploration/components/AcmgVerdict/index.tsx
src/views/Variants/Exploration/variantColumns.tsx

feat: CLIN-1156 change acmg cell design

---

src/views/Variants/Exploration/variantColumns.tsx

fix: CLIN-1143 scroll horizontal

---

package.json
src/index.js

fix: CLIN-1170 eslint warning correction theme

---

src/locales/en.json
src/locales/fr.json

fix: CLIN-1174 fix rqdm section title

---

src/views/Variants/Exploration/Patient/facets.tsx

Ajout filtre rqdm dans panel de gène

fix: CLIN-1175 ajout rqdm dans gene

---

src/graphql/utils/nameTransformer.tsx

fix: CLIN-1153 modifier facette status affecté

---

src/graphql/utils/nameTransformer.tsx
src/locales/fr.json

fix: CLIN-1153 fix traduction

---

src/api/user/models.ts
src/views/Archives/index.tsx
src/views/Variants/Exploration/Patient/PageContent/tabs/Variants/index.tsx

Story : https://ferlab-crsj.atlassian.net/browse/CLIN-1054
Subtask : https://ferlab-crsj.atlassian.net/browse/CLIN-1232
Added sync with users-api on more tables :
- archives
- patient variants

fix: CLIN-1232 handled sync with users-api on more tables

---

src/locales/en.json
src/locales/fr.json
src/views/Snv/Entity/SummaryPanel/Frequency/index.module.scss
src/views/Snv/Entity/SummaryPanel/Frequency/index.tsx

- Changement du titre tableau RQDM
- Ajout summary Row au tableau

fix: CLIN-1277 modifier tableau rqdm

---

src/views/Prescriptions/Search/index.tsx

changement du autocomplete pour un input et sort automatique du tableau
Avant:
Après:

feat: CLIN-1240 changement boite autocomplete

---

src/api/fhir/models.ts
src/components/Variant/PatientTags.tsx
src/components/uiKit/PositionTag/index.tsx
src/graphql/prescriptions/helper.tsx
src/graphql/prescriptions/queries.tsx
src/views/Cnv/Exploration/Patient/index.tsx
src/views/Snv/Exploration/Patient/index.tsx

Faire afficher le tag parent au lieux de toujours afficher le tag cas-index

fix: CLIN-1098 afficher le tag parent

---

src/views/Prescriptions/Search/index.tsx

permettre la recherche avec numéro de requête complet

fix: CLIN-1240 rentrer numero complet requête

---

src/components/icons/QgBadgeIconHighIcon.tsx
src/components/icons/QgBadgeIconLowIcon.tsx
src/style/themes/clin/dist/antd.css
src/views/Snv/Exploration/variantColumns.tsx
src/views/Snv/components/GQLine/index.module.scss
src/views/Snv/components/GQLine/index.tsx
src/views/Snv/components/OccurrenceDrawer/index.tsx

- Ajout badge pour les valeurs de GQ dans tableau variant snv + tiroir occurrence
- Rouler `npm run thme` pour le bug du tiroir d'occurence

fix: CLIN-1276 ajouter badge GQ

---

README.md
env-prod
env-qa
env-staging
src/api/hpo/index.ts
src/api/hpo/models.ts
src/components/PhenotypeTree/index.tsx
src/components/Prescription/Analysis/AnalysisForm/ReusableSteps/PatientIdentification/index.tsx
src/components/Prescription/components/ClinicalSignsSelect/index.module.scss
src/components/Prescription/components/ClinicalSignsSelect/index.tsx
src/components/Prescription/components/HistoryAndDiagnosisData/index.module.scss
src/components/Prescription/components/HistoryAndDiagnosisData/index.tsx
src/components/Prescription/components/PatientDataSearch/index.tsx
src/components/Prescription/utils/ramq.ts
src/components/uiKit/form/InputDateFormItem/index.tsx
src/locales/en.json
src/locales/fr.json
src/store/prescription/slice.ts
src/utils/EnvVariables.ts

- CLIN-1359 : Fix hpo tree
- CLIN-1377 : Error message for health condition input
- CLIN-1306 : Set default EP

fix: CLIN-1359 multiple fixes

---

src/views/Snv/Exploration/variantColumns.tsx

fix quand on va sur l'onglet patient et on ne peux plus faire back pour revenir a l'onglet résumé

fix: CLIN-1267 back ne fonctionne pas

---

src/locales/en.json
src/locales/fr.json
src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx

- Enlever tooltip cellule colonne AA et ADN codant
- Ajouter tooltip sur le (C)

fix: CLIN-1280 MAJ tableau consequences

---

.husky/pre-commit
package-lock.json
package.json

global config with ferlab/config

feat: CLIN-1287 use global ferlabconfig

---

.github/workflows/coverage.yml
.github/workflows/coverage/Dockerfile
.husky/pre-commit
commitlint.config.js
env-github
package.json
src/components/Layout/Footer/tests/__snapshots__/Footer.test.jsx.snap

closes: https://ferlab-crsj.atlassian.net/browse/CLIN-1441
Ajouter un 'threshold' de 20% pour les tests
Coverage doit être rouler avant les push et lors des PR

feat: CLIN-1441 test threshold

---

src/views/Snv/components/GQLine/index.tsx
src/views/Snv/components/OccurrenceDrawer/SequencingMetricModal/index.tsx

problème d'affichage des données lorsque la valeur était à 0 affichait empty   '--'

fix: CLIN-1413 mauvais data

---

package-lock.json
package.json
src/components/uiKit/FilterList/CustomFilterContainer.tsx
src/views/Snv/Entity/SummaryPanel/AcmgCriteria/index.tsx
src/views/Snv/Entity/SummaryPanel/Clinical/index.tsx

- closes #[3242](https://ferlab-crsj.atlassian.net/browse/FLUI-4)
Provide the ability to include items without data in quantitative researches.

feat: FLUI-4 selection no data in range filter

---

package-lock.json
package.json
src/locales/en.json
src/locales/fr.json
src/views/Snv/components/GeneUploadIds/index.tsx

Mettre a jour ferlab-ui
Ajouter la limite d'item pour le geneUpload ID

feat: CLIN-1297 mettre a jour ferlabUI

---

src/graphql/patients/models/Patient.ts
src/graphql/patients/queries.tsx
src/views/Archives/columns.tsx
src/views/Archives/index.tsx

fix le lien des requêtes dans page archive pour la page de la prescription associer a la requêtes

fix: CLIN-1132 fix request link

---

src/views/Prescriptions/Entity/ClinicalInformationCard/components/ClinicalSign/index.tsx

Problème erreur 500 lorsque 1 valeur de signe clinique.

fix: CLIN-1491 fix erreur 500 signe clinique

---

src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/index.tsx

- erreur 500 avec fetus
- problème lorsque 1 signe clinique

fix: CLIN-1498 fix problème prescription

---

src/style/themes/clin/_theme.template.scss
src/style/themes/clin/antd/buttons.less
src/style/themes/clin/dist/antd.css

fix: CLIN-1217 Button and QueryBuilder styling

---

src/components/Prescription/components/PatientDataSearch/index.tsx

We want to be able to update the MRN if it was null before.

fix: CLIN-1270 allow mrn update if new

---

src/components/Variant/PatientTags.tsx

Ajout numéro échantillon dans la page variant

feat: CLIN-1407 ajout numero echantillon

---

package.json
src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx
src/views/Snv/Entity/SummaryPanel/Consequences/tests/consequences.spec.js

- Changer la source pour la colonne AA et Adn codant
- Changement coverageThreshold approuver par @francisl 
Exemple pour --> chr16:g.70265041A

fix: CLIN-1518 valeur AA et adnc

---

src/locales/en.json
src/locales/fr.json
src/views/Snv/Exploration/tests/variant.spec.js
src/views/Snv/Exploration/variantColumns.tsx

- Changement valeur colonne gnomAD exome pour genome
- Changement tooltip pour colonne gnomAD

fix: CLIN-1530 changement valeur gnomad

---

src/graphql/variants/queries.tsx

fix: CLIN-1530 fix data

---

package-lock.json
package.json

- closes [3242](https://ferlab-crsj.atlassian.net/browse/CLIN-1514)
fix table overflow in prescription tab switch
@kstonge

fix: CLIN-1514 downgrade antd version to solve table issue

---

src/locales/en.json
src/locales/fr.json
src/views/Snv/Exploration/variantColumns.tsx

- Mettre colonne action a la fin de la liste
- Changer tooltip gnomAD CLIN-1530

fix: CLIN-1480 mettre colonne action a la fin

---

src/views/Snv/Exploration/tests/variant.spec.js

fix: CLIN-1530 fix test

---

src/style/themes/clin/dist/antd.css

- run theme pour réglé problème tiroir

fix: CLIN-1545 run theme

---

src/views/Snv/Exploration/tests/variant.spec.js
src/views/Snv/Exploration/variantColumns.tsx

fix erreur 500 lorsqu'il y a un varsome mais pas de classification.

fix: CLIN-1538 fix 500 error when no classifications

---

package-lock.json
package.json

see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/182
corrige l'erreur des pillules qui ne se supprime pas
la pillule de no data disparait avec un modification

fix: FLUI-16 pills delete error

---

src/components/uiKit/search/PrescriptionAutoComplete/index.tsx

Be able to search Analyses with mother / father IDs
Requires: https://github.com/Ferlab-Ste-Justine/clin-fhir-server/pull/155

feat: CLIN-1127 add mother father id in search analyses

---

src/components/Variant/PatientTags.tsx
src/components/Variant/index.module.scss

- Ajout lien vers page prescription
- Fix mauvais numéro de prescription

fix: CLIN-1524 fix numero prescription

---

src/views/Snv/Entity/SummaryPanel/Clinical/conditions/OmimConditionCell.tsx
src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx

- fix typo omin
- ajouter traduction see more see less

fix: CLIN-1513 typo

---

src/api/fhir/models.ts
src/graphql/prescriptions/actions.tsx
src/graphql/prescriptions/queries.tsx
src/views/Prescriptions/Entity/AnalysisCard/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Consanguinity/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/tests/paraclinique.spec.js
src/views/Prescriptions/Entity/ClinicalInformationCard/index.tsx

- Mettre section autre examen paraclinique avec le bon nom a la fin
- Ajouter champ panel Reflex
- Afficher bonne valeur de consanguinité
- Ajouter unité pour examen paraclinique

fix: CLIN-1483 fix autre prescription

---

package-lock.json
package.json

https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/187

fix: CLIN-1526 fix source to prevent the error

---

package-lock.json
package.json
src/locales/en.json
src/locales/fr.json
src/utils/helper.ts
src/utils/tests/helper.spec.js
src/utils/translation.ts
src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/PrescriptionTable.test.jsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Prescriptions/Search/components/table/SequencingTable/index.tsx
src/views/Prescriptions/Search/components/table/SequencingTable/tests/SequencingTable.test.jsx
src/views/Prescriptions/Search/components/table/SequencingTable/tests/__snapshots__/SequencingTable.test.jsx.snap
src/views/Prescriptions/utils/export.ts
src/views/Prescriptions/utils/tests/export.test.js

feat: CLIN-1550 - download

---

src/graphql/prescriptions/actions.tsx
src/graphql/prescriptions/queries.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/ClinicalSign/index.tsx

traduire age onset des signe clinique

fix: CLIN-1483 traduction age onset

---

src/views/Snv/utils/constant.ts

Changement nombre rangé tableau SNV

feat: CLIN-1572 pageSize tableau SNV

---

src/views/Snv/Exploration/variantColumns.module.scss
src/views/Snv/Exploration/variantColumns.tsx

fix le shadow manquant quand on a une colonne fixed avec texte ellipsis

fix: CLIN-1573 shadow fixed colonne

---

src/style/themes/clin/antd/table.less
src/style/themes/clin/dist/antd.css

mettre a jour le style pour que les colonnes fix dans les tableau sois également zébré

fix: CLIN-1567 ajout zebra colonne fix

---

src/style/themes/clin/antd/table.less
src/style/themes/clin/dist/antd.css

fix la couleur des cellules des colonnes triés

fix: CLIN-1604 fix couleur colonne trié

---

src/style/themes/clin/antd-clin-theme.less
src/style/themes/clin/antd/buttons.less
src/style/themes/clin/dist/antd.css
src/views/Snv/Exploration/components/OtherActions/index.tsx
src/views/Snv/Exploration/variantColumns.tsx

fix alignement et grosseur icone colonne action

fix: CLIN-1582 fix alignement icon action

---

src/locales/en.json
src/locales/fr.json
src/store/savedFilter/thunks.ts

fix: CLIN-1577 add message notification when adding or deleting filter

---

src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Prescriptions/components/Links/index.tsx

- Ajout colonne lien avec lien vers page variant dans le tableau de prescription

feat: CLIN-1588 ajout colonne lien

---

src/views/Snv/utils/constant.ts

remettre 20 rangés par page pour le tableau snv variant

fix: CLIN-1620 remettre 20 par page variant snv

---

package-lock.json
package.json

mettre a jour ferlab/ui pour régler le problème de tooltip dans les subColomns

fix: CLIN-1614 mettre a jour ferlab

---

src/graphql/cnv/models.ts
src/graphql/cnv/queries.ts
src/utils/helper.ts
src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
src/views/Cnv/Exploration/components/IGVModal/index.module.scss
src/views/Cnv/Exploration/components/IGVModal/index.tsx
src/views/Cnv/Exploration/variantColumns.tsx

- Ajout colonne action tableau CNV
- Ajout des du modal igv dans l'onglet variant CNV

feat: CLIN-1623 ajout track cnv

---

src/views/Cnv/Exploration/components/IGVModal/index.tsx
src/views/Snv/components/IGVModal/index.tsx

changer ordre des track dans CNV et SNV

fix: CLIN-1651 ordre track

---

src/App.tsx
src/components/Layout/ContentWithHeader/index.module.scss
src/components/Layout/ContentWithHeader/index.tsx
src/components/Layout/FixedLayout.tsx
src/components/Layout/index.module.scss
src/components/Table/StaticTableHeight.tsx
src/index.css
src/views/Prescriptions/Search/components/Sidebar/index.module.scss
src/views/Prescriptions/Search/components/Sidebar/index.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Prescriptions/Search/components/table/SequencingTable/index.tsx
src/views/Prescriptions/Search/index.module.scss
src/views/Prescriptions/Search/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx

closes https://ferlab-crsj.atlassian.net/browse/CLIN-1625
https://user-images.githubusercontent.com/98903/208188273-ab72788f-728d-4eb0-8142-7bd17f7edae8.mov

feat: CLIN-1625 tableaux de prescription scroll intérieur

---

src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx

Ajout expendableCell dans le tableau de conséquences dans variant entity

fix: CLIN-1440 ajout expendableCell tableau variant entity

---

src/App.tsx
src/components/Layout/FixedContentWithFooter/index.module.scss
src/components/Layout/FixedContentWithFooter/index.tsx
src/views/Snv/Exploration/Patient/PageContent/index.module.scss
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.module.scss
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/components/VariantContentLayout/index.module.scss
src/views/Snv/Exploration/components/VariantSearchLayout/index.tsx

corrige probleme avec https://ferlab-crsj.atlassian.net/browse/CLIN-1625
https://user-images.githubusercontent.com/98903/211105974-68d81d44-3acd-40de-8705-39096ebe68d0.mov

fix: CLIN-1625 update scroll in variant prescription

---

src/components/Layout/FixedContentWithFooter/index.module.scss
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.module.scss
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.module.scss

resout le problème de la page rqdm variant et la visibilité du scroll.

fix: CLIN-1625 update scroll in variant prescription rqdm

---

cypress/e2e/Colonnes/TableauVariants.cy.ts
cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/PageVariantResume.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
cypress/e2e/Consultation/TiroirOccurrence.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/plugins/index.ts
cypress/support/commands.ts
cypress/support/index.d.ts

feat: CLIN-1529 Add Cypress tests

---

src/components/Variant/PatientTags.tsx
src/components/Variant/tests/PatientTags.spec.jsx
src/views/Cnv/Exploration/Patient/tests/CnvPatient.test.jsx
src/views/Cnv/Exploration/Patient/tests/__snapshots__/CnvPatient.test.jsx.snap
src/views/Prescriptions/Entity/RequestTable.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Snv/Exploration/Patient/tests/SnvPatient.test.jsx
src/views/Snv/Exploration/Patient/tests/__snapshots__/SnvPatient.test.jsx.snap

fix: CLIN-1667 - sample

---

src/components/Igv/index.tsx
src/components/Igv/tests/__snapshots__/igv.test.jsx.snap
src/components/Igv/tests/igv.test.jsx

Corrige la fenetre IGV qui ne s'affiche plus si on switch entre SNV <=> SNV

feat: CLIN-1605 IGV browser creation

---

src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx
src/views/Snv/Exploration/Patient/facets.tsx
src/views/Snv/Exploration/Rqdm/facets.tsx

Fix les commentaires pour le spliceAI

fix: CLIN-1626 spliceAi

---

src/api/user/models.ts
src/graphql/variants/actions.tsx
src/utils/helper.ts
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Prescriptions/Search/components/table/SequencingTable/tests/__snapshots__/SequencingTable.test.jsx.snap
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
src/views/Snv/Exploration/tests/variant.spec.js
src/views/Snv/Exploration/variantColumns.tsx
src/views/Snv/utils/constant.ts

Fix la pagination suivant / précédent
Enlever Tri sur colonne QG et Zygosité
Fix le trie sur les colonne gnomAD et RQDM

fix: CLIN-1678 fix afterseach

---

src/locales/fr.json

fix: CLIN-1693 mettre la ligature oe pour soeur

---

src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/variantColumns.tsx

update horizontal scroll https://ferlab-crsj.atlassian.net/browse/CLIN-1625
https://user-images.githubusercontent.com/98903/216166062-6ab521e2-ec03-4ad7-b251-9e1bd7b44c4e.mov

fix: CLIN-1625 scroll horizontal

---

cypress.config.ts
cypress/e2e/Consultation/PagePrescription.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/PageVariantResume.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TiroirOccurrence.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Navigation/Variants.cy.ts
cypress/e2e/Recherches/PageAccueil.cy.ts
cypress/e2e/Recherches/PagePrescriptions.cy.ts
cypress/plugins/index.ts
cypress/support/commands.ts

Update et amélioration des tests Cypress

feat: CLIN-1529 Cypress tests

---

src/views/Snv/Exploration/variantColumns.tsx

Mise en commentaire des colonnes pLI et LOEUF en attendant la normalisation du tableau

fix: CLIN-1673 enlever colonne pLI et LOEUF

---

src/views/Snv/Entity/SummaryPanel/Clinical/columns.tsx
src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx
src/views/Snv/Exploration/variantColumns.tsx
src/views/Snv/components/ConsequencesCell/index.tsx

Normaliser les valeur clinvar et conséquence.

fix: CLIN-1652 normaliser conséquence et clinvar

---

src/components/icons/geneOverlapType/Type1Icon.tsx
src/components/icons/geneOverlapType/Type2Icon.tsx
src/components/icons/geneOverlapType/Type3Icon.tsx
src/locales/en.json
src/locales/fr.json
src/views/Cnv/Exploration/components/GenesModal/geneColumns.tsx
src/views/Cnv/Exploration/components/GenesModal/index.tsx
src/views/Cnv/Exploration/components/GenesModal/utils.ts

feat: CLIN-1685 add cnv gene overlap type

---

src/views/Prescriptions/Search/index.tsx

fix le problème d'autocomplete dans le tableau de requête et de prescription lorsque nous ne somme pas à la première page.

fix: CLIN-1581 fix autocomplete

---

src/views/Prescriptions/utils/export.ts
src/views/Prescriptions/utils/tests/export.test.js
src/views/Snv/components/Download/index.tsx

Add `donors.patient_id` in the download TSV arranger request

feat: CLIN-1730 - TSV add patientid

---

package-lock.json
package.json
src/components/Table/StaticTableHeightXY.tsx
src/utils/translation.ts
src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
src/views/Prescriptions/Search/components/table/SequencingTable/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/variantColumns.tsx

feat: CLIN-1625 new column management with fixed scroll table

---

src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx

- Changement design information conséquence
- Ajout pli et loeuf
@luclemo

feat: CLIN-1728 ajout pli et loeuf entite variant

---

package-lock.json
package.json
src/components/Table/StaticTableHeightXY.tsx
src/views/Snv/Exploration/variantColumns.tsx

fix CLIN-1625 performance issue and fixed column ordering

fix: CLIN-1625 performance issue and fixed column ordering

---

package-lock.json
package.json

fix: CLIN-1625 performance issue and fixed column reset and 500

---

src/views/Archives/columns.tsx
src/views/Archives/tests/Archives.test.jsx
src/views/Archives/tests/__snapshots__/Archives.test.jsx.snap

ajout sort sur certaine colonne du tableau  archives

fix: CLIN-1616 sort de colonne archives

---

src/views/Snv/Entity/SummaryPanel/Consequences/index.tsx

Retiré le mot "Score" de SpliceAi **Score**

fix: CLIN-1735 fix SpliceAi nom

---

src/views/Snv/Exploration/variantColumns.module.scss
src/views/Snv/Exploration/variantColumns.tsx

fix: CLIN-1752 mettre text ellipsis clinvar

---

package-lock.json
package.json
src/style/themes/clin/_theme.template.scss
src/style/themes/clin/main.scss

feat: CLIN-1739 migration ferlab

---

src/auth/rpt.ts

Avoid spamming token requests
**before**
**after**

feat: CLIN-1754 - token once

---

src/views/Snv/Exploration/variantColumns.tsx

fix: CLIN-1727 variant column size reduction

---

src/locales/en.json
src/locales/fr.json
src/utils/translation.ts

Changement du tooltips pour l'arrangement des colonnes

fix: CIN-1656 tooltip columns

---

cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
cypress/e2e/Consultation/PageVariantResume.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/support/commands.ts

- CLIN-1529 Adjustments to Cypress tests
- CLIN-1691 Add and adjust Cypress tests

Add and adjust Cypress tests

---

env-prod
env-qa
env-staging

Remettre le bouton de traduction en QA

feat: CLIN-878 remettre bouton traduction

---

src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.module.scss
src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
src/views/Cnv/Exploration/components/VariantContentLayout/index.module.scss
src/views/Cnv/Exploration/variantColumns.tsx

Corrige le problème de scroll horizontale tableau CNV

fix: CLIN-1775 fix scroll tableau cnv

---

cypress/e2e/Colonnes/TableauArchives.cy.ts
cypress/e2e/Colonnes/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/FormulairesPrescription/CreationPrescription.cy.ts
src/components/Prescription/AnalysisChoiceModal/index.tsx
src/components/Prescription/components/ClinicalSignsSelect/index.tsx
src/components/Prescription/components/HistoryAndDiagnosisData/index.tsx
src/components/Prescription/components/PatientDataSearch/index.tsx
src/components/Prescription/index.tsx
src/views/Home/components/ActionButton/index.tsx
src/views/Home/index.tsx

Ajouts/ajustements des tests Cypress
- CLIN-1742 Adjustments to Cypress tests
- CLIN-1616 Adjustments to Cypress tests
- CLIN-1750 Add Cypress creation prescription test
À noter que j'ai ajouté des attributs "data-cy" dans des régions possiblement pauvres en tests unitaires. Ne pas tenir compte du seuil de couverture des tests unitaires pour cette PR.

Add cypress tests

---

src/views/Cnv/Exploration/components/GenesModal/geneColumns.tsx
src/views/Cnv/Exploration/variantColumns.tsx
src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
src/views/Prescriptions/Search/components/table/SequencingTable/columns.tsx
src/views/Snv/Exploration/variantColumns.tsx

Ajout de colonne tribale manquante

feat: CLIN-1777 ajout tri sur colonne

---

src/views/Snv/Exploration/variantColumns.tsx

close ticket CLIN-1777 et CLIN-1792
Enlever certaine colonne dans le tableau snv

fix: CLIN-1777 supprimer tri colonne

---

src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx

Ajout de gnomad genome 3.0 et ualité du génotype a la requête de het composite
Avant
Après

feat: CLIN-1784 ajout query het composite

---

cypress/e2e/Colonnes/TableauCNVsPatient.cy.ts
cypress/e2e/Colonnes/TableauPrescriptions.cy.ts
cypress/e2e/Colonnes/TableauRequetes.cy.ts
cypress/e2e/Colonnes/TableauVariants.cy.ts
cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TiroirOccurrence.cy.ts

Adjustments to Cypress tests
- CLIN-1758
- CLIN-1777

feat: CLIN-1758 Adjustments to Cypress tests

---

package-lock.json
package.json
src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx

- mise a jour ferlab-ui
- ajout noData dans gnomad 3.0
- ajout ad_alt

fix: CLIN-1784 hc nodata + ad_alt

---

src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx

fix: CLIN-1784 gnomAD 3_1_1

---

src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/locales/en.json
src/locales/fr.json
src/views/Snv/Exploration/tests/variant.spec.js
src/views/Snv/Exploration/variantColumns.tsx

Changement dans la colonne gnomad tableau SNV de 2.1.1 pour 3.1.1

fix: CLIN-1813 changement gnomad 3_1_1

---

src/views/Archives/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx

Enlever le tooltip sur les colonne qui on le tri

fix: CLIN-1744 enlever tooltip sort

---

src/views/Snv/Exploration/components/OtherActions/index.tsx

changement du lien pour litvar

fix: CLIN-1830 lien litvar2

---

src/graphql/variants/models.ts
src/utils/helper.ts
src/views/Snv/Entity/SummaryPanel/Summary/index.tsx
src/views/Snv/Exploration/variantColumns.tsx

fix erreur 500 en production 
https://ferlab-crsj.atlassian.net/browse/CLIN-1847

fix: CLIN-1847 erreur 500 avec gnomad_genomes_3_1_1

---

src/providers/ApolloProvider.tsx

Will never happend in PROD, caused by Cypress daily tests

fix: CLIN-1890 Graphql FHIR max count

---

cypress.config.ts
cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
cypress/e2e/Colonnes/TableauArchives.cy.ts
cypress/e2e/Colonnes/TableauCNVsPatient.cy.ts
cypress/e2e/Colonnes/TableauPrescriptions.cy.ts
cypress/e2e/Colonnes/TableauRequetes.cy.ts
cypress/e2e/Colonnes/TableauVariants.cy.ts
cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/PageAnalyseBioinfo.cy.ts
cypress/e2e/Consultation/PagePrescription.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/PageVariantResume.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
cypress/e2e/Consultation/TableauPrescriptions.cy.ts
cypress/e2e/Consultation/TableauRequetes.cy.ts
cypress/e2e/Consultation/TiroirOccurrence.cy.ts
cypress/e2e/Facettes/Dictionnaires.cy.ts
cypress/e2e/Facettes/PagePrescriptions.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/FormulairesPrescription/CreationPrescription.cy.ts
cypress/e2e/Navigation/Logout.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Recherches/PageAccueil.cy.ts
cypress/e2e/Recherches/PageArchives.cy.ts
cypress/e2e/Recherches/PagePrescriptions.cy.ts
cypress/support/commands.ts

Ajustements aux tests Cypress
- Utilisation d'une session pour améliorer la performance en temps
- Modifications suite à la correction de CLIN-1890

Clin 1529 cypress tests

---

release-ticket
src/graphql/cnv/models.ts
src/graphql/cnv/queries.ts
src/views/Cnv/Exploration/Patient/facets.tsx

Add CNVs Genes facets
https://portal-ui-clin-1630.qa.cqgc.hsj.rtss.qc.ca/

feat: CLIN-1630 add CNVs genes facets

---

src/views/Prescriptions/utils/tests/export.test.js

fix: CLIN-1882 - TUs

---

.husky/post-checkout
README.md

- closes #CLIN-1825
[JIRA TICKET](https://ferlab-crsj.atlassian.net/browse/CLIN-1825)
- la documentation est compréhensible
-

fix: CLIN-1825 partage du theme dans submodule documentation

---

release-ticket
src/components/uiKit/search/PrescriptionAutoComplete/tests/__snapshots__/PrescriptionAutoComplete.test.jsx.snap
src/views/Archives/tests/__snapshots__/Archives.test.jsx.snap
src/views/Prescriptions/Entity/tests/__snapshots__/RequestTable.test.jsx.snap
src/views/Prescriptions/Search/components/table/PrescriptionTable/tests/__snapshots__/PrescriptionTable.test.jsx.snap
src/views/Prescriptions/Search/components/table/SequencingTable/tests/__snapshots__/SequencingTable.test.jsx.snap
src/views/Snv/Exploration/variantColumns.tsx
src/views/Snv/utils/constant.ts

CLIN-2023
https://ferlab-crsj.atlassian.net/browse/CLIN-2023
Data with exomiser
https://portal-ui-clin-2023.qa.cqgc.hsj.rtss.qc.ca/snv/exploration/patient/807421/807417

feat: CLIN-2023 remove exomiser sort

---

cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts

- complements #CLIN-2019
[CLIN-2019](https://ferlab-crsj.atlassian.net/browse/CLIN-2019) [Prod] Le tri sur le score Exomiser ne fonctionne pas

feat: CLIN-2019 Adjust Cypress tests

---

cypress/e2e/Colonnes/TableauVariants.cy.ts
cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts

- complements #CLIN-2011
[CLIN-2011](https://ferlab-crsj.atlassian.net/browse/CLIN-2011) [TableauxSNV] Mettre un sort sur la colonne Gène

feat: CLIN-2011 Adjust Cypress tests

---

package-lock.json
package.json
release-ticket
src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2015
Mettre le bon ordre de colonne dans le tableau SNV patient
_[CLIN-2015](https://ferlab-crsj.atlassian.net/browse/CLIN-2015)_
...

fix: CLIN-2015 ordre colonne exo

---

release-ticket
src/views/Snv/Exploration/variantColumns.tsx

feat: CLIN-2011 wip

---

cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
cypress/e2e/Colonnes/TableauFichiers.cy.ts
cypress/e2e/Colonnes/TableauPrescriptions.cy.ts
cypress/e2e/Colonnes/TableauRequetes.cy.ts
cypress/e2e/Consultation/PagePrescription.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
cypress/e2e/Consultation/TableauPrescriptions.cy.ts
cypress/e2e/Consultation/TableauRequetes.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- complements #CLIN-1979
[CLIN-1979](https://ferlab-crsj.atlassian.net/browse/CLIN-1979) Refonte navigation

feat: CLIN-1979 Adjust Cypress tests

---

release-ticket
src/graphql/variants/models.ts
src/locales/en.json
src/locales/fr.json
src/views/Snv/Entity/index.tsx
src/views/Snv/Entity/tests/VariantEntityPage.test.js
src/views/Snv/Entity/tests/__snapshots__/VariantEntityPage.test.js.snap
src/views/Snv/utils/tests/helper.spec.js

le champ `variant_type` a change de type `string` => `array`
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2087)
Before: erreur 500
After:

fix: CLIN-2087 variant entity page

---

release-ticket
src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx

- closes #CLIN-1855
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1855)
https://portal-ui-clin-1855.qa.cqgc.hsj.rtss.qc.ca/snv/exploration
https://github.com/Ferlab-Ste-Justine/clin-portal-ui/assets/98903/da3e9838-3a7a-4cfb-900f-fd55b2ed2027
[Steps to validate](https://ferlab-crsj.atlassian.net/browse/FLUI-42)
@kstonge

fix: CLIN-1855 page navigation return error

---

release-ticket
src/locales/en.json
src/locales/fr.json
src/utils/translation.ts

- closes #CLIN-1748
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1748)
...

fix: CLIN-1748 traduction

---

release-ticket
src/views/Snv/utils/helper.ts

[JIRA LINK]https://ferlab-crsj.atlassian.net/browse/CLIN-1574
...

fix: CLIN-1574 fixed query when patient id combined with OR

---

release-ticket
src/hooks/useSavedFiltersActions.ts

[JIRA LINK]https://ferlab-crsj.atlassian.net/browse/CLIN-2107
...

fix: CLIN-2107 fixed broken shared filter navigation

---

release-ticket

- closes #CLIN-1558
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1558)
...

fix: CLIN-1558 couleur modal

---

.github/pull_request_template.md

- closes #clin-2140
[[JIRA LINK]
Acceptance Criterias](https://ferlab-crsj.atlassian.net/browse/CLIN-2140)

fix: clin-2140 remove mention

---

release-ticket
src/api/fhir/models.ts
src/graphql/prescriptions/actions.tsx
src/graphql/prescriptions/queries.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/ClinicalSign/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/index.tsx
src/views/Prescriptions/Entity/constants.ts

- closes #CLIN-1644
Afficher aussi les signes cliniques et les valeurs des examens paracliniques en français dans la page d’une prescription.
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1644)
...

fix: CLIN-1644 traduction signe clinique et paraclinique

---

release-ticket
src/views/Snv/components/ConsequencesCell/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2102)
/prescription/entity/923933#variants
With `consequences = intro & splice donor` filter enabled

feat: CLIN-2102 null aa_change

---

cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
release-ticket
src/graphql/utils/dictionaries.ts
src/locales/en.json
src/locales/fr.json

- closes #CLIN-2201
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2201)
...

fix: CLIN-2201 ajout dictionnaire

---

cypress/e2e/Consultation/PageVariantPatients.cy.ts
release-ticket
src/views/Snv/Entity/PatientPanel/index.tsx

- closes #CLIN-1662
Tableau snv patient
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1662)
...

fix: CLIN-1662 pagination qui disparait

---

release-ticket
src/views/Archives/columns.tsx
src/views/Snv/Entity/PatientPanel/columns.tsx

- closes #CLIN-1664
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1664)
...

fix: CLIN-1664 tris colonne multiple

---

cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/PageVariantResume.cy.ts
cypress/e2e/Consultation/TableauArchives.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauCNVsPatientSomatic.cy.ts
cypress/e2e/Consultation/TableauCouvertureGenique.cy.ts
cypress/e2e/Consultation/TableauFichiers.cy.ts
cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
cypress/e2e/Consultation/TableauPrescriptions.cy.ts
cypress/e2e/Consultation/TableauRequetes.cy.ts
cypress/e2e/Consultation/TableauVariants.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
cypress/e2e/Facettes/PageCNVsPatient.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Facettes/PageVariantsPatient.cy.ts
cypress/e2e/Facettes/PageVariantsPatientSomatic.cy.ts
cypress/e2e/Recherches/PagePrescriptions.cy.ts
cypress/e2e/Requetes/ValidationVariantsPatient.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- complements #CLIN-1529
- Add Validation Request tests
- Add Expand all/Collapse all tests
- Redesign Sort/Filter tests
- Some adjustments

feat: CLIN-1529 Add and adjust Cypress tests

---

cypress/e2e/Consultation/TableauVariantsPatientSomatic.cy.ts
cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts
cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
src/graphql/utils/dictionaries.ts

- closes #CLIN-2127
Exploration(Banque)/Patient/Analyse 
SNV(Prescription)/Panel RQDM|Gène/RQDM 
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2127)
...

fix: CLIN-2127 [Dictionnaire] Ajuster les valeurs des facettes des panels

---

package-lock.json
package.json

[FLUI-85](https://ferlab-crsj.atlassian.net/browse/FLUI-85)
Juste une mise à jour de la version de ferlab.

feat: FLUI-85 add data cy on facets

---

release-ticket
src/views/Cnv/Exploration/Patient/index.tsx
src/views/Cnv/utils/helper.ts
src/views/Cnv/utils/tests/helper.spec.js
src/views/Prescriptions/Entity/GenericCoverage/index.tsx
src/views/Prescriptions/Entity/Tabs/Variants/cnv/index.tsx
src/views/Prescriptions/Entity/Tabs/Variants/snv/index.tsx
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Patient/index.tsx
src/views/Snv/utils/helper.ts
src/views/Snv/utils/tests/helper.spec.js

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1872)
By ServiceRequest and Patient
- regarder les variants du patient BATCH PARCAS Trio prob (permet de tester la selection par patient)
- regarder les variants du numero dossier: MRN-283804 (ce patient a un prescription batch + a la main)
...
@kstonge

fix: CLIN-1872 variants by analysis

---

cypress/e2e/Consultation/TableauCouvertureGenique.cy.ts
cypress/e2e/Telechargement/TableauCouvertureGenique.cy.ts
src/components/Download.tsx
src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
src/views/Prescriptions/Entity/GenericCoverage/index.tsx
src/views/Prescriptions/Search/index.tsx
src/views/Prescriptions/utils/export.ts
src/views/Prescriptions/utils/tests/export.test.js
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2325)
...

fix: CLIN-2325 - download TSV

---

src/views/Cnv/Exploration/variantColumns.module.scss
src/views/Cnv/Exploration/variantColumns.tsx
src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
src/views/Snv/Exploration/variantColumns.module.scss
src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2342
Colonne changeais de place dans les tableau, 
Changement effectuer sur les tableaux: SNV(tous), CNV, couverture génique
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2342)
...

fix: CLIN-2342 Comportement weird des colonnes

---

src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx

- closes #CLIN-2153
Problème de pagination qui change dans les tableaux mais pas dans le select de pagination
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2153)

fix: CLIN-2153 [Search After] Glitch avec le dropdown X/écran

---

cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient.cy.ts
cypress/fixtures/ExportTableauVariantsPatient.json
src/locales/en.json
src/locales/fr.json
src/views/Snv/Exploration/variantColumns.module.scss
src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2337
- Transmission : Mettre à jour les tag et réduire la largeur de la colonne 
- OMIM Mettre une largeur pour 2 Tags seulement et Wrapper les > 2 tags 
- Rétrécir la largeur de Zyg. 
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2337)
...

feat: CLIN-2337 ajustement tableau

---

src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2346
changer l’hyperlien actuel pour celui vers OMIM gènes : [genes.omim_gene_id](https://www.notion.so/ferlab/genes-omim_gene_id-d60172bb13364af2a7aa3254ff2a24e8) du gène picked
ex : sur le gène  WDR37 mettre l’hyperlien [https://www.omim.org/entry/618586](https://www.omim.org/entry/618586?search=WDR37&highlight=wdr37)
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2346)

feat: CLIN-2346 Mettre les liens vers OMIM gene (SNV)

---

src/components/uiKit/FilterList/CustomFilterSelector.tsx
src/utils/query.ts
src/utils/tests/query.spec.js
src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
src/views/Prescriptions/Search/index.tsx
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2368)
@kstonge

fix: CLIN-2368 async sqon with references

---

cypress/e2e/Consultation/TableauPrescriptions.cy.ts
cypress/e2e/Consultation/TableauRequetes.cy.ts
cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts
cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
cypress/e2e/Facettes/PageCNVsPatient.cy.ts
cypress/e2e/Facettes/PagePrescriptions.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Facettes/PageVariantsPatient.cy.ts
cypress/e2e/Facettes/PageVariantsPatientSomatic.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Recherches/PagePrescriptions.cy.ts
cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

Complements [FLUI-85](https://ferlab-crsj.atlassian.net/browse/FLUI-85) [Cypress] Ajouter des data-cy aux facettes

feat: FLUI-85 Use data-cy in Cypress tests

---

cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
src/graphql/utils/dictionaries.ts

feat: CLIN-2294 removed no data from consequences list

---

src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2380
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2380)
...

feat: CLIN-2380 fix QD width

---

cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts
src/graphql/utils/dictionaries.ts

#FEAT : Ajout de SCID au dictionnaire de panel
- closes #CLIN-2352
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2352)
...

feat: CLIN-2352 add scid panel dictionairies

---

src/utils/IGV.ts
src/utils/tests/IGV.spec.js
src/views/Cnv/Exploration/components/IGVModal/index.tsx
src/views/Snv/components/IGVModal/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2410)

feat: CLIN-2410 IGV CNV by variant type

---

cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts
cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts
src/graphql/utils/Filters.tsx
src/graphql/utils/dictionaries.ts
src/graphql/utils/tests/filters.spec.ts

- closes #CLIN-2385
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2385)
...

fix: CLIN-2385 fix dictionnaire

---

cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
cypress/e2e/Consultation/PageAnalyseBioinfo.cy.ts
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauCouvertureGeniqueSomatic.cy.ts
cypress/e2e/Consultation/TableauFichiers.cy.ts
cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic.cy.ts
cypress/e2e/Facettes/PageCNVsPatient.cy.ts
cypress/e2e/Facettes/PageVariantsPatient.cy.ts
cypress/e2e/Facettes/PageVariantsPatientSomatic.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes [CLIN-2445](https://ferlab-crsj.atlassian.net/browse/CLIN-2445)
Mettre à jour les tests Cypress avec les ajustements accumulées.

feat: CLIN-2445 Add and adjust Cypress tests

---

cypress/e2e/Consultation/TableauVariants.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic.cy.ts
src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/views/Snv/Exploration/variantColumns.tsx

[JIRA LINK](https://cancer.sanger.ac.uk/cosmic/search?q=)
...

fix: CLIN-2463 nouvelle url cmc

---

package-lock.json
package.json
src/index.js
src/utils/EnvVariables.ts
src/utils/sentry/localStorageIntergretions.ts

https://ferlab-crsj.atlassian.net/browse/CLIN-2381

feat: CLIN-2381 sentry logging

---

package-lock.json

[CLIN-2504](https://ferlab-crsj.atlassian.net/browse/CLIN-2504)
Selected custom pill color is blue not yellow.
[CLIN-2504]: https://ferlab-crsj.atlassian.net/browse/CLIN-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: CLIN-2504 theme

---

env-github
env-prod
env-staging
package-lock.json

- closes [#TICKET_NUMBER](https://ferlab-crsj.atlassian.net/browse/CLIN-2507)
Mettre a jour les configuration de sentry

fix: CLIN-2507 mise a jour fichier env

---

src/utils/helper.ts
src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
src/views/Prescriptions/Entity/GenericCoverage/index.tsx
src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
src/views/Snv/utils/constant.ts

fix: CLIN-2399 fixed scroll to top when changing page in tables (#612)

---

src/locales/en.json
src/locales/fr.json

- closes CLIN-2494
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2494)
...

fix: CLIN-2494 fix inheritant code Mi typo

---

cypress/e2e/Colonnes/TableauVariants.cy.ts
cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauCNVsPatientSomatic.cy.ts
cypress/e2e/Consultation/TableauVariants.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic.cy.ts
cypress/e2e/Facettes/DictionnairesVariants.cy.ts
cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
cypress/e2e/Facettes/PageVariants.cy.ts
cypress/e2e/Facettes/PageVariantsPatient.cy.ts
cypress/fixtures/ExportTableauVariants.json
cypress/support/commands.ts
src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/locales/en.json
src/locales/fr.json
src/utils/translation.ts
src/views/Snv/Exploration/Rqdm/facets.tsx
src/views/Snv/Exploration/variantColumns.tsx

- closes #Clin-2500
- Afficher exomiser dans tableau Exploration
- Filtrer Exomiser dans Facette Exploration
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2500)
- Colonne Crit E. affiche les scores comme demandé
- Facette Exomiser, filtre les scores comme demandé
...

feat: CLIN-2500 exomiser max

---

cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts
src/views/Cnv/Exploration/components/GenesModal/geneColumns.tsx
src/views/Cnv/Exploration/components/GenesModal/index.tsx
src/views/Cnv/Exploration/components/GenesModal/tests/utils.spec.js

- closes #CLIN-2347
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2347)
...

feat: CLIN-2347 changement hyperlien gene cnv

---

src/locales/en.json
src/views/Snv/Exploration/variantColumns.module.scss
src/views/Snv/Exploration/variantColumns.tsx

- closes CLIN-2479
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2479)
...

fix/CLIN-2479 Max Fra column is now sortable

---

cypress/e2e/Facettes/PageVariants.cy.ts

[CLIN-2504](https://ferlab-crsj.atlassian.net/browse/CLIN-2504)
- custom pill must be blue in QB
[CLIN-2504]: https://ferlab-crsj.atlassian.net/browse/CLIN-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: CLIN-2504 style commit hash

---

src/graphql/cnv/models.ts
src/graphql/cnv/queries.ts
src/graphql/variants/models.ts
src/graphql/variants/queries.tsx
src/utils/tests/formatNumber.spec.js
src/views/Cnv/Exploration/components/IGVModal/index.tsx
src/views/Cnv/Exploration/components/IGVModal/tests/IGVModel.test.jsx
src/views/Cnv/Exploration/components/IGVModal/tests/__snapshots__/IGVModel.test.jsx.snap
src/views/Snv/components/IGVModal/index.tsx
src/views/Snv/components/IGVModal/tests/IGVModel.test.jsx
src/views/Snv/components/IGVModal/tests/__snapshots__/IGVModel.test.jsx.snap

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2598)

feat: CLIN-2598 IGV with parents

---

src/components/Variant/PatientTags.tsx

#FEAT : Changer tag analyse header pour l'abbréviation
- closes #CLIN-2583
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2583)
...

feat: CLIN-2583 changement tag analyse

---

src/views/Prescriptions/Entity/Tabs/Variants/utils.ts
src/views/Snv/Exploration/Patient/PageContent/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2654)

fix: CLIN-2654 hotfix

---

src/locales/fr.json
src/utils/translation.ts

fix: CLIN-2625 added missing translation for required field

---

src/views/Prescriptions/Entity/constants.ts

fix: CLIN-2551 changed empty field value

---

src/views/Cnv/Exploration/variantColumns.tsx

fix: CLIN-2657 - CNV dragen 500

---

src/views/Prescriptions/Entity/ParentCard/index.tsx
src/views/Prescriptions/Entity/PatientCard/PatientContent/index.tsx
src/views/Prescriptions/Entity/PatientCard/index.tsx
src/views/Prescriptions/Entity/Tabs/Details/index.tsx

- closes PRESC-153
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-153)
...

feat: PRESC-153 add org reference after patient id

---

cypress/e2e/Consultation/TableauVariantsPatient_1.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient_3.cy.ts
cypress/e2e/Consultation/TableauVariants_1.cy.ts
cypress/e2e/Consultation/TableauVariants_3.cy.ts
src/locales/en.json
src/locales/fr.json
src/utils/constants.ts
src/views/Snv/Exploration/variantColumns.tsx

- ACMG F: Tag et hyperlien
- ClinVar: Tag et hypelien
- ACMG E. : Tag seulement
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2707)

feat: CLIN-2707 hyperlien classifications

---

src/components/Layout/ScrollContentWithFooter/index.tsx
src/components/Layout/shared.module.scss
src/views/BioInfoAnalysis/index.tsx

- closes CLIN-2700
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2700)
...

fix: CLIN-2700 container wrapper to have enough min height to push footer down

---

src/api/fhir/index.ts
src/api/fhir/models.ts
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/index.tsx
src/views/Prescriptions/Entity/Tabs/Details/index.tsx

- closes CLIN-2713
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2713)
...

fix: CLIN-2713 no more undefined for paraclinical exams in prescription detail page

---

src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx
src/views/Prescriptions/Entity/ClinicalInformationCard/index.tsx

- closes CLIN-2714
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2714)
...

fix: CLIN-2714 CGH is a complex paraclinical exam

---

src/api/index.ts
src/views/Prescriptions/Entity/Tabs/Files/index.tsx

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2795)

fix: CLIN-2795 timeout and searchValue

---

cypress/e2e/Consultation/TableauVariantsPatientPaired_1.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic_1.cy.ts
cypress/e2e/Facettes/PageVariantsPatientPaired.cy.ts
cypress/e2e/Facettes/PageVariantsPatientSomatic.cy.ts
cypress/fixtures/ExportTableauVariantsPatientPaired.json
cypress/fixtures/ExportTableauVariantsPatientSomatic.json
src/graphql/utils/dictionaries.ts
src/graphql/variants/models.ts
src/locales/en.json
src/locales/fr.json
src/utils/translation.ts
src/views/Prescriptions/utils/export.ts
src/views/Snv/Exploration/Patient/facets.tsx
src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2524
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2524)
...

feat: CLIN-2524 colonne facette all analyses

---

cypress/e2e/Consultation/PagePrescription.cy.ts
cypress/support/commands.ts
src/api/fhir/models.ts
src/graphql/prescriptions/queries.tsx
src/views/Prescriptions/Entity/AnalysisCard/index.tsx
src/views/Prescriptions/Entity/ParentCard/index.tsx
src/views/Prescriptions/Entity/PatientCard/index.tsx

- closes CLIN-2711
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2711)
...

fix: CLIN-2711 get ep from patient managing org ref

---

src/graphql/prescriptions/actions.tsx
src/graphql/prescriptions/queries.tsx
src/locales/en.json
src/locales/fr.json
src/views/Prescriptions/Entity/AbsentParentCard/index.tsx
src/views/Prescriptions/Entity/ParentCard/index.tsx
src/views/Prescriptions/Entity/PatientCard/index.tsx
src/views/Prescriptions/Entity/Tabs/Details/index.tsx

- closes CLIN-2774
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2774)
...

fix: CLIN-2774 show absent parents

---

src/graphql/patients/models/Patient.ts
src/graphql/patients/queries.tsx
src/utils/IGV.ts
src/views/Snv/components/IGVModal/index.tsx

- closes #CLIN-2523
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2523)

feat: CLIN-2523 igv exome

---

cypress/e2e/Consultation/TableauCNVsPatient.cy.ts
cypress/e2e/Consultation/TableauCNVsPatientSomatic.cy.ts
cypress/e2e/Consultation/TableauCouvertureGenique.cy.ts
cypress/e2e/Consultation/TableauPrescriptions.cy.ts
cypress/e2e/Consultation/TableauRequetes.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientPaired_3.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientSomatic_3.cy.ts
cypress/e2e/Consultation/TableauVariantsPatient_3.cy.ts
cypress/e2e/Consultation/TableauVariants_3.cy.ts
cypress/e2e/Consultation/TiroirOccurrencePaired.cy.ts
cypress/e2e/Consultation/TiroirOccurrenceSomatic.cy.ts
cypress/e2e/Filtres/PageVariantsPatientPaired.cy.ts
cypress/support/commands.ts
cypress/support/index.d.ts

- closes #CLIN-2845
[CLIN-2845](https://ferlab-crsj.atlassian.net/browse/CLIN-2845)
[CLIN-2845]: https://ferlab-crsj.atlassian.net/browse/CLIN-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CLIN-2845 Adjust Cypress tests

---

src/utils/queryBuilder.ts
src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
src/views/Prescriptions/Entity/GenericCoverage/index.tsx
src/views/Prescriptions/Entity/GenericCoverage/tests/GenericCoverage.test.jsx
src/views/Prescriptions/Entity/GenericCoverage/tests/__snapshots__/GenericCoverage.test.jsx.snap
src/views/Prescriptions/Entity/Tabs/Variants/snv/index.tsx
src/views/Prescriptions/Entity/Tabs/Variants/snvTN/index.tsx
src/views/Prescriptions/Entity/Tabs/Variants/snvTN/tests/SNVTN.test.jsx
src/views/Prescriptions/Entity/Tabs/Variants/snvTN/tests/__snapshots__/SNVTN.test.jsx.snap
src/views/Snv/Exploration/Patient/PageContent/index.tsx
src/views/Snv/Exploration/Patient/facets.tsx
src/views/Snv/Exploration/Rqdm/facets.tsx
src/views/Snv/utils/constant.ts
src/views/Snv/utils/tests/constant.spec.js

- closes #CLIN-2584
Nouveau query builder id pour séparer les pills/savedFilter de tableau germinaux, tumeur only et tumeur normal
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2584)

feat: CLIN-2584 saveFilter snv

---

cypress/e2e/Consultation/PageVariantResume.cy.ts
src/views/Snv/Entity/SummaryPanel/Clinical/conditions/HpoConditionCell.tsx

- closes #CLIN-2863
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2863)
...

fix: CLIN-2863 traduction

---

src/views/Prescriptions/Entity/ParentCard/index.tsx

- closes PRESC-199
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/PRESC-199)
...

fix: PRESC-199 show correct affected status for parents

---

ci/pipeline.yml

- closes #CLIN-2915
[CLIN-2915](https://ferlab-crsj.atlassian.net/browse/CLIN-2915)
[CLIN-2915]: https://ferlab-crsj.atlassian.net/browse/CLIN-2915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CLIN-2915 Parallelize in 8

---

src/views/Snv/Exploration/variantColumns.tsx

- closes #CLIN-2897
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2897)
...

fix: CLIN-2897 fix bioanalyse width

---

src/locales/en.json
src/locales/fr.json
src/views/Prescriptions/Entity/ClinicalInformationCard/components/Paraclinique/index.tsx

- closes CLIN-2763
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2763)
...

fix: CLIN-2763 fix CGH concept translation display

---

src/views/Prescriptions/Entity/PatientCard/PatientContent/index.tsx

- closes CLIN-2922
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2922)
...

fix: CLIN-2922 patient folder organisation only if both ref and mrn present

---

src/utils/IGV.ts
src/utils/tests/IGV.spec.js

- closes #CLIN-2546
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2546)
...

feat: CLIN-2546 igv hyperExome track

---

cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts

- closes #CLIN-2972
- relate to #CLIN-2971
[CLIN-2972](https://ferlab-crsj.atlassian.net/browse/CLIN-2972)
[CLIN-2971](https://ferlab-crsj.atlassian.net/browse/CLIN-2971)
[CLIN-2972]: https://ferlab-crsj.atlassian.net/browse/CLIN-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLIN-2971]: https://ferlab-crsj.atlassian.net/browse/CLIN-2971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: CLIN-2972 Adjust Cypress tests related to CLIN-2971

---

cypress/e2e/Consultation/TableauCouvertureGenique.cy.ts
src/views/Prescriptions/Entity/GenericCoverage/columns.tsx

- closes #CLIN-2872
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2872)
...

fix: CLIN-2872 gc cnv link

---

Makefile
README.md
cypress/e2e/Consultation/PageVariantPatients.cy.ts
cypress/e2e/Consultation/TableauVariantsPatientPaired_2.cy.ts
cypress/e2e/Navigation/Pages.cy.ts
cypress/e2e/Recherches/TableauCouvertureGenique.cy.ts
cypress/support/commands.ts
package-lock.json
package.json
src/components/Layout/Header/index.module.scss
src/locales/en.json
src/locales/fr.json
src/utils/translation.ts

- Fix button text styles issues (hover, active, focus, focus-visible)
- Fix button in QueryBuilder Header
- Fix proTable itemCount header
- Add a Makefile

Fix: clin-2635 text button style and ProTable item counter

---

Makefile
package-lock.json
package.json
scripts/less-var-to-css-var.js
src/components/uiKit/FilterList/Filters.module.css
src/views/Prescriptions/components/Links/index.tsx
tsconfig.paths.json

FIX: CLIN-2868 add correct style for link buttons
https://ferlab-crsj.atlassian.net/browse/CLIN-2868

FIX: CLIN-2868 add correct style for link buttons
