- src/locales/en.json
- src/locales/fr.json
- src/views/Variants/Entity/SummaryPanel/Consequences/index.tsx
> fix: CLIN-1092 Separer colonne transcrit en 2

- src/views/Variants/Entity/PatientPanel/index.tsx
you can test here http://localhost:2005/variant/entity/10-100296259-G-A/patients
- avoid importing all of lodash (`import _ from "lodash"`)
- compute data for all charts by traversing data only once (a gain factor of 5X on my machine)
> refactor: CLIN-1104 optimize pie charts data computation

- src/views/Prescriptions/Search/index.tsx
ajouter `:` au label de la recherche.
> fix: CLIN-1151 update prescription search design fix

- src/graphql/prescriptions/actions.tsx
- src/graphql/prescriptions/queries.tsx
- src/graphql/queries.ts
- src/hooks/graphql/useGetExtendedMappings.ts
- src/providers/ApolloProvider.tsx
Some local no-so-rigourous-metrics:
with this commit (new instances created multiple times)
ApolloProvider.tsx:63 test: 0.007080078125 ms
ApolloProvider.tsx:63 test: 0.007080078125 ms
ApolloProvider.tsx:63 test: 0.005859375 ms
ApolloProvider.tsx:63 test: 0.009033203125 ms
ApolloProvider.tsx:63 test: 0.005859375 ms
ApolloProvider.tsx:63 test: 0.008056640625 ms
ApolloProvider.tsx:63 test: 0.004150390625 ms
ApolloProvider.tsx:63 test: 0.01220703125 ms
ApolloProvider.tsx:63 test: 0.012939453125 ms
before this commit (one instances per backend) 
test2: 2.27001953125 ms
ApolloProvider.tsx:54 test2: 0.181884765625 ms
ApolloProvider.tsx:54 test2: 0.34521484375 ms
ApolloProvider.tsx:54 test2: 0.277099609375 ms
ApolloProvider.tsx:54 test2: 0.2080078125 ms
ApolloProvider.tsx:54 test2: 0.14111328125 …
> fix: CLIN-1182 make sure apollo client cache some results

- src/views/Snv/components/GeneUploadIds/index.tsx
Linked to: https://github.com/Ferlab-Ste-Justine/clin-variant-etl/pull/213 (where the case un-sensitive stuff is done)
The change in front-end is only the after request when the UI compute a list of found genes from the response.
> feat: CLIN-1247 search gene case sensitive

- src/views/Prescriptions/Entity/index.tsx
Comment from this: https://ferlab-crsj.atlassian.net/browse/CLIN-1457
They want Forbidden instead of NotFound if prescription not visible for the current user
> feat: CLIN-14757 - forbidden prescription

- src/components/uiKit/FilterList/CustomFilterContainer.tsx
fix l'application des filtres a 'ou'  par défault. Maintenant va juste s'appliquer pour les types Range.
> fix: FLUI-4 or only when range filter

- src/views/Snv/Exploration/variantColumns.tsx
- src/views/Snv/components/OccurrenceDrawer/index.tsx
- fix affichage manquant dans la colonne origine parental snv
- Afficher correctement la valeur origine parental dans le tiroir des occurrences
> fix: CLIN-1472 affichage origineParental variant

- src/views/Snv/components/ConsequencesCell/consequences.ts
- src/views/Snv/components/ConsequencesCell/tests/consequences.spec.js
Fix this issue: https://ferlab-crsj.atlassian.net/browse/CLIN-1501
This issue seems related to `symbol = null` we can have the same consequence multiple times.
The fix will guaranty unicity for all symbols
> feat: CLIN-1501 distinct consequences

- src/views/Snv/Exploration/variantColumns.tsx
- Mettre la colonne actions figer a droite
Avant
Maintenant
@kstonge
> feat: CLIN-1480 mettre colonne Actions figer a droite

- src/api/arranger/models.ts
- src/utils/suggestions.ts
- src/utils/tests/suggestions.spec.js
- src/views/Home/components/VariantSearchBox/index.tsx
Example of suggestion:
```
"type": "variant",
"suggest": [
{
"weight": 4,
"input": [
"chr1:g.156530566G>C",
"rs732362",
"1-156530566-G-C"
]
},
{
"weight": 2,
"input": [
"IQGAP3",
"ENST00000361170",
"ENSG00000183856"
]
}
],
```
We want to ignore what's linked to genes, in the ETL this part has been put inside the weight 2 section.
Solution: filter and keep the weight >= 4 matchs
> feat: CLIN-1072 - filter  variants suggestions

- package-lock.json
- Reverts package-lock full update
- Adds cypress (only) dependencies to package-lock file
> fix: CLIN-1529 cypress dependencies

- src/utils/helper.ts
- src/utils/searchPageTypes.ts
- src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
- src/views/Prescriptions/Search/components/table/SequencingTable/index.tsx
- src/views/Prescriptions/Search/index.tsx
- src/views/Prescriptions/utils/export.ts
- src/views/Prescriptions/utils/tests/export.test.js
**New implementation of export as TSV feature**
This implementation allows to download even what's not displayed in the current page when user select **all** rows.
From a performance point of view, the requests to list the elements to download are always done but the limit size is 0 if nothing selected (good workaround to my opinion).
> feat: CLIN-1550 - export as TSV - with all

- src/views/Home/index.module.scss
ajouter max-width a la page d'acceuil
avant:
Après:
> fix: CLIN-1692 largeur acceuil

- package-lock.json
- package.json
- closes https://ferlab-crsj.atlassian.net/browse/CLIN-1625
fix reordring and display when initial columns are provided
fix :
> fix: CLIN-1625 performance issue and fixed column ordering

- src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx
Changement de la query pour les Hét. composé non potentiel
Avant:
Après:
> fix: CLIN-1814 query hc non potentiel

- src/views/Archives/helper.ts
- src/views/Archives/index.tsx
- src/views/Archives/tests/helper.spec.js
- src/views/BioInfoAnalysis/FilesCard/index.tsx
Refactoring of how **archive** and **bioinformatics** files are computed.
> feat: CLIN-1737 - refactoring FHIR files

- src/api/fhir/index.ts
> fix: CLIN-1845 - ignore cache for codes request

- src/components/uiKit/PositionTag/index.tsx
- src/graphql/prescriptions/helper.tsx
Changer le tag parent pour le tag correspondant au membre de la famille dans page variant
Avant
Après
> fix: CLIN-1811 tag specific famille

- cypress/e2e/Facettes/Dictionnaires.cy.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
Ajout de tests pour s'assurer que les valeurs hardcodées des dictionnaires restent à jour avec les données existantes.
Dans une deuxième itération, j'aimerais récupérer les valeurs des dictionnaires (src/graphql/utils/dictionaries.ts) au lieu de les hardcoder dans les tests.
> feat: CLIN-1780 Add Cypress tests

- release-ticket
- src/views/Snv/Exploration/variantColumns.tsx
- src/views/Snv/utils/constant.ts
- closes #CLIN-2019
Exomiser score column is now sortable
[JIRA LINK]https://ferlab-crsj.atlassian.net/browse/CLIN-2019
...
> fix: CLIN-2019 activated sort on exomiser score column

- release-ticket
- src/graphql/utils/Filters.tsx
- src/graphql/utils/tests/filters.spec.ts
- closes #CLIN-2031
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2031)
- 1 et 0 sont afficher comme des numéro
- true et false demeure true et false
voir les filtres sous 'Variant'
> fix: CLIN-2031 number 1 and 0 correctly display in filters

- release-ticket
- src/utils/constants.ts
- src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
- src/views/Prescriptions/Search/components/table/SequencingTable/columns.tsx
- src/views/Prescriptions/utils/export.ts
- src/views/Prescriptions/utils/tests/export.test.js
- src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx
- closes #CLIN-1923
Afficher un tiret au lieu d’une case vide dans tous les tableaux.Pour les exports tsv, afficher 2 tirets
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1923)
...
> fix: CLIN-1923 placeholder case vide

- release-ticket
- src/views/Snv/Exploration/variantColumns.tsx
- src/views/Snv/utils/tests/helper.spec.js
- closes #CLIN-2082
En ce moment cliquer sur le + ajoute le symbole dans la query active. il faut changer ce comportement pour ajouter le symbol dans une nouvelle barre de Query. 
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2082)
...
> feat: CLIN-2082 nouvelle query colonne gene

- release-ticket
- src/utils/translation.ts
- closes #CLIN-2114
Dans tous les tableaux, traduire “No available data” par “Aucun résultat”
[[JIRA LINK]
](https://ferlab-crsj.atlassian.net/browse/CLIN-2114)
...
> fix: CLIN-2114 traduire nodata tableau

- cypress/e2e/Consultation/TiroirOccurrence.cy.ts
- release-ticket
- src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
- src/views/Snv/Exploration/variantColumns.tsx
- src/views/Snv/components/OccurrenceDrawer/HcDescription/index.tsx
- src/views/Snv/components/OccurrenceDrawer/index.tsx
#FEAT: ajout locus requete hc
- closes #CLIN-1870
Actuellement, la requête des variants rares ne liste que les locus du variant pour lequel le tiroir est ouvert.
Il faut ajouter le locus de ce dernier à la requête pour avoir tous les HC listés
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-1870)
...
> feat: CLIN-1870 ajout locus requete hc

- src/locales/en.json
- closes #CLIN-2230
En anglais: “Download report”
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2230)
...
> fix: CLIN-2230 [Typo] Les boutons Download devraient être Sentence case

- src/utils/translation.ts
- closes #CLIN-2156
La valeur affichée dans la requête doit être dans le même format que dans la facette.
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2156)
...
> fix: CLIN-2156 [Query] Formatter la valeur comme dans la facette

- src/views/Cnv/Exploration/variantColumns.module.scss
- src/views/Snv/Exploration/variantColumns.module.scss
- src/views/Snv/components/ConsequencesCell/index.module.scss
#BUG | remove double tooltip on safari
- closes https://ferlab-crsj.atlassian.net/browse/CLICE-245
no double tooltip on safari
> fix: CLIN-2283 duplicate tooltip on safari

- src/views/Snv/Exploration/variantColumns.tsx
- closes #CLIN-2319
Les variants exportés dans le TSV doivent afficher les mêmes valeurs que celles listées dans le tableau
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2319)
...
> fix: CLIN-2319 tsv picked gene symbol

- src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
- src/views/Cnv/Exploration/variantColumns.tsx
- src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
- src/views/Prescriptions/Entity/GenericCoverage/index.tsx
- src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
- src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
- src/views/Snv/Exploration/variantColumns.tsx
- closes #CLIN-2033
L’affichage des colonnes est brisé quand on les affiche toutes et qu’il n’y a pas de données dans le tableau
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2033)
...
> fix: CLIN-2033 [Tableaux] Affichage brisé lorsqu'il n'y a pas de donnée

- src/api/user/models.ts
- src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
- closes #CLIN-2344
Les colonnes ne s’affichent pas dans le bon ordre et un Reset et nécessaire au switch entre la page des variants d’un patient germinaux et somatiques.
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2344)
...
> fix: CLIN-2344  Glitch au switch entre variants germinaux et somatiques

- src/utils/helper.ts
- src/utils/tests/helper.spec.js
- src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
- src/views/Prescriptions/Entity/GenericCoverage/index.tsx
- src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
- src/views/Prescriptions/Search/components/table/SequencingTable/index.tsx
- src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
- src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
- closes #CLIN-2366
Pour reproduire:
- Trier une colonne
- Cliquer 2 fois pour retirer le trie de la colonne
- Cliquer sur Suivant
- Cliquer sur Précédent
-
[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2366)
...
> fix: CLIN-2366 [Search After] La combinaison Next/Prev. avec le sort ne fonctionne pas

- src/views/Cnv/Exploration/variantColumns.tsx
- closes #CLIN-2384
Dans la page des CNVs d’un patient, la colonne #Gènes semble trop étroite et il ne devrait pas y avoir de lien si le nombre est 0.
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2384)
...
> fix: CLIN-2384 fix cnv nb genes

- cypress/e2e/Consultation/TiroirOccurrence.cy.ts
- src/views/Snv/components/OccurrenceDrawer/index.tsx
#FEAT  : Afficher la zygosité dans sa forme allélique dans l'occurence
- closes #CLIN-2558
Dans le volet d'occurrence la zygosité est affichée avec HET, HOM et HEM il faut la mettre sous la forme 1/1 0/1 1, comme dans les tableau pour la colonne Zyg.
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2558)
...
> feat: CLIN-2558 zygosity occurence

- cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts
- cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts
- src/graphql/utils/dictionaries.ts
- closes #CLIN-2686
**CNV**  
Facette “variant type ”(Values GAINLOH, CNLOH )
Facette “Filtre (Dragen) ” (Values binCount, segmentMean)
**SNV**
Facette “Filtre (Dragen) ” (Value low_tlen)
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2686)
> feat: CLIN-2686 ajout dictionaries cnv snv

- src/views/Snv/Exploration/variantColumns.tsx
- closes #CLIN-2842
L’affichage de la valeur est sur une seule ligne.
Pour tous les tableau contenant cette colonne.
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2842)
...
> fix: CLIN-2842 rqdm width

- cypress/e2e/AccesUtilisateurs/ParRole.cy.ts
- src/views/Prescriptions/Entity/RequestTable.tsx
- src/views/Prescriptions/Entity/tests/__snapshots__/RequestTable.test.jsx.snap
- src/views/Prescriptions/components/Links/index.tsx
- closes #CLIN-2862
Dans le cas d’un docteur (ex. Félix), puisqu’il n’a pas accès aux liens, ils ne sont pas affichés, ce qui laisse la colonne vide.
Si l’utilisateur ne pourra jamais avoir accès à ces liens, on cache la colonne liens au complet.
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2862)
...
> feat: CLIN-2862 enlever link si non autorise

- src/locales/en.json
- src/locales/fr.json
- closes #CLIN-2890
Valider la pertinence du quasi doublon pour le filters.group entre analysis_code et analysis.code
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2890)
> fix: CLIN-2890 fix doublon

- src/views/Cnv/Exploration/variantColumns.module.scss
- src/views/Snv/Exploration/variantColumns.module.scss
- closes #CLIN-2867
Aligner à gauche l’en-tête Actions des tableaux
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2867)
...
> fix: CLIN-2867 fix colonne actions

- src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
- src/views/Prescriptions/utils/export.ts
- closes #CLIN-2864
Priorisation d'affichage à gauche des avatars de tous les LDMs d'un utilisateur
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2864)
...
> fix: CLIN-2864 assignment order

- cypress/fixtures/ExportTableauPrescriptions.json
- src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
- src/views/Prescriptions/utils/export.ts
- src/views/Prescriptions/utils/tests/export.test.js
- closes #CLIN-2962
[JIRA LINK](https://ferlab-crsj.atlassian.net/browse/CLIN-2962)
...
> fix: CLIN-2962 add empty field assignments tsv
